name: Update Data & Rebuild Svelte Page

on:
  push:
  schedule:
    - cron: '0 11 * * 1-5'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Init
        run: yarn
      - name: Fetch
        run: yarn fetch
      - name: Process
        run: yarn process
      - name: Commit Change
        uses: stefanzweifel/git-auto-commit-action@v4
      - name: Build
        run: yarn build
      - name: Deploy
        uses: s0/git-publish-subdir-action@v2.3.0
        env:
          REPO: self
          BRANCH: page
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
